create table Clients (ID SERIAL PRIMARY KEY, FIRST_NAME VARCHAR, LAST_NAME VARCHAR,
EMAIL VARCHAR, PASSWORD VARCHAR, TELNUMBER VARCHAR, CREATEDBY INT,  CREATEDAT VARCHAR);

create table Dish (ID SERIAL PRIMARY KEY, Dishes INT ARRAY, NAME VARCHAR, DESCRIPTION VARCHAR, 
DISHID INT, AVAILABILITY BOOLEAN, COST FLOAT, CREATEDBY INT,CREATEDAT VARCHAR,);

create table Order (ID SERIAL PRIMARY KEY, Dishes INT ARRAY, CLIENTID INT references Client(ID), TABLENUMBER INT,
 CREATEDBY INT,  CREATEDAT VARCHAR);

CREATE TABLE Payment (ID INT PRIMARY KEY, CREATEDAT DATE, CREATEDBY INT, AMOUNT INT, CLIENTID INT);


